language: node_js
node_js:
  - "node"

sudo: false
cache:
  directories:
    - node_modules

before_install:
  - openssl aes-256-cbc -K $encrypted_8b6653878ef7_key -iv $encrypted_8b6653878ef7_iv -in .ci/deploy_key.enc -out .ci/deploy_key -d # decrypt deploy key
  - chmod 600 .ci/deploy_key
  - "ssh-keygen -p -P $DEPLOY_KEY_PASSPHRASE -N '' -f .ci/deploy_key" # change to no passphrase for ssh-add
  - eval "$(ssh-agent -s)" # start the ssh agent
  - ssh-add .ci/deploy_key
  - git remote add main-code git@github.com:test-splo/test1.git -f
  - git config --global user.email "spinylobster@outlook.com" && git config --global user.name "Travis CI"
  - git config --global merge.ours.driver true && git subtree pull -P . main-code HEAD -m "code mix from main-code"
  - ssh-keygen -y -f .ci/deploy_key > .ci/deploy_key.pub && ssh-add -d .ci/deploy_key && rm -f .ci/deploy_key*

deploy:
  provider: openshift
  user: spinylobster0713@gmail.com
  password:
    secure: JLNAyJ4FP8wq1gr/PlT6UauVnIkt1EzL9l4NY4MkLtMpzpLlUsf1coN5nVDi/XCMM2QZieDTN0ZHnRThnRG36cJ5gtp6f+Xbkig2RaGZRcYHlwnElC6n9sVLcpZlrIqWm9rjjQ0+JyE72fXyufomDwZAQce1CrzWUc4Gy7l2kaTTrZ8LfstbM7jxH+V+JjHQYrIBK92eIORto+yNWGf8eoKi09TvfJVcJCWdrT9zxqq542DMTAjSX9Iiv9nrdPxpNCw6F4BFTO/AxE1Uf7KuIApRConF/4K4gJFW38Lli+Ubl25yHBjy2kXAgky7YEOCXo2dfGGCpgkzq6cJUThS/SpffTTRbFb7bq3OkpqO7b6am4zg3XanerYrzP/5qaL67ILRnUDxghdy9Urr9E9Mvw5TXMUVYjSUWYcKrcuIkrhcW7AP80eLsgs5QgIZUt7C7C8PLDvXiVR8oXDiiiypLZ5YqmBAxPegw8H0RVHrZUqnJNIBnU2J7NS1tQ574h+usnpnnGCi56ptqqLsq4m3GN87kZWNbLxInaHJoJv3s/6VvPNlxP4M9T/k9wgSb3kIpoTqdRtBn808pvKK1fP0XjZHD9VntyoGlR0zKX9IBNx/UVGCdjAiSVW0AB2AKJdtSD19o+VsTcmXX/auu5W02LOJWI2/zrHadanWsesZl+U=
  app: nodeapp
  domain: spinylobster
  on:
    repo: test-splo/test1_deploy-openshift
  deployment_branch: HEAD
  edge: true
